spring.application.name=homelab-backend
springdoc.swagger-ui.path=/api

# Set proxmox.enabled=true and provide credentials to load real Proxmox data.
proxmox.enabled=true
proxmox.base-url=https://proxmox.homelab.local/api2/json
proxmox.node=pve
proxmox.api-token=manuel@pam!homelab-monitor=63c03c54-5baf-42fc-9c9d-39c41d841658
proxmox.insecure-ssl=true